inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Exclude:
    - config/environments/*
    - config/initializers/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

AllCops:
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - bin/bundle
  NewCops: enable